### ISSUE TITLE
Update SystemExecutioner to investigate adding a delay before exiting to allow for checking if the app has exited

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/dropwizard-service-utilities#6]

**Comment by sleberknight** [comment]
Note: the original comment in the code was:

```java
// TODO: Should we wait some number of seconds as a daemon thread before shutting ourselves down to see if we actually
//       die?  How to do that??
```

**Comment by sleberknight** [comment]
My original TODO comment doesn't really make much sense...why would it matter whether this thread or some other one shuts us down? Answer: it doesn't. And, if ewe _know_ that we need to shut ourselves down, might as well do it quickly and fail fast so our monitoring can detect the problem more quickly...

**Comment by sleberknight** [comment]
Instead, I did some experimenting with `SystemExecutioner` and changing it to use an `ExecutionStrategy` internally. The code I produced lets you easily use `SystemExecutioner` in unit tests by creating it with a `NoOpExecutionStrategy` instead of the default `SystemExitExecutionStrategy`. 

Does something like this make sense? I will push a branch up for discussion and consideration.

**Comment by sleberknight** [comment]
Here is the pull request: #90

**Comment by sleberknight** [comment]
Closing this investigation. See #91
